localstack:
  enabled: true
  region: us-east-1
  endpoint: http://localhost:4566
  credentials:
      access-key: test
      secret-key: test

cloud:
  aws:
    credentials:
      access-key: x
      secret-key: y
    region:
      static: eu-west-2
    stack:
      auto: false

server:
  port: 8080

application:
  bucket:
    name:
      input: s3.spring.input
      output: s3.spring.output

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

folder:
  input:
    text: E:\Files\Incoming\CustomerSpringFolder
    json:

files:
  input:
    json: E:\\Files\\Incoming\\Json\\left.json
  output:
    text: E:\\Files\\Outgoing\\SpringOut.txt

