localstack:
  enabled: true
  region: eu-west-2
  endpoint: http://localhost:4566
  credentials:
      access-key: test
      secret-key: test

cloud:
  aws:
    credentials:
      access-key: xxx
      secret-key: yyy
    region:
      static: eu-west-2
    stack:
      auto: false

server:
  port: 8080